# server:
#   port: ${SERVER_PORT:8082}

# spring:
#   datasource:
#     url: ${DB_URL:jdbc:mysql://localhost:3306/notification_db}
#     username: ${DB_USERNAME:root}
#     password: ${DB_PASSWORD:bookonthego123}
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect

#   mail:
#     host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
#     port: ${MAIL_PORT:587}
#     username: ${MAIL_USERNAME:0c173abb9049b9}
#     password: ${MAIL_PASSWORD:6e17fd28697f3f}
#     properties:
#       mail:
#         smtp:
#           auth: true
#           starttls:
#             enable: true
#     protocol: smtp

#   thymeleaf:
#     prefix: classpath:/templates/
#     suffix: .html
#     mode: HTML
#     cache: false

# twilio:
#   account:
#     sid: ${TWILIO_ACCOUNT_SID:ACb07fa78f5404843e69f6d09ece0b3030}
#   auth:
#     token: ${TWILIO_AUTH_TOKEN:328b333df1aa8410fc9ae151af005d54}
#   phone:
#     number: ${TWILIO_PHONE_NUMBER:+13306424779}

# stripe:
#   key: ${STRIPE_KEY:test_stripe_key}

# microservices:
#   payment-service-url: ${PAYMENT_SERVICE_URL:http://payment-service-url/endpoint}
#   event-service-url: ${EVENT_SERVICE_URL:http://event-service-url/endpoint}
#   booking-service-url: ${BOOKING_SERVICE_URL:http://booking-service-url/endpoint}
#   auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8081}
